import React, { useState, useRef, useEffect } from "react";
import { Route, Routes, BrowserRouter } from "react-router-dom";
import Home from "./pages/Home";
import Map from "./pages/Map";
import TopProducts from "./pages/TopProducts";
import QlikObject from "./components/qlikObject";

function App() {
  const [qlikGlobal, setQlikGlobal] = useState(null);
  const [App, setApp] = useState(null);
  const env = useRef(null);

  const connectToQlik = async () => {
    if (!App) {
      fetch("./environment.json")
        .then((response) => {
          return response.json();
        })
        .then((e) => {
          let urlParts = window.location.href.split("/");
          let qlikProtocol = urlParts[0].replace(":", "");
          let qlikHost = urlParts[2];
          let qlikPort = qlikProtocol === "https" ? 443 : 80;
          let qlikVirtualProxy =
            urlParts["3"] !== "extensions" ? `/${urlParts[3]}` : "";
          if (qlikVirtualProxy === "/#") {
            qlikVirtualProxy = "";
          }
          console.log(e);
          // default to the config settings if they exist
          qlikProtocol = e.qlikProtocol || qlikProtocol;
          qlikHost = e.qlikHost || qlikHost;
          qlikPort = e.qlikPort || qlikPort;
          if (typeof e.qlikVirtualProxy !== "undefined") {
            qlikVirtualProxy = e.qlikVirtualProxy;
          }
          const baseUrl = `${qlikProtocol}://${qlikHost}:${qlikPort}${qlikVirtualProxy}`;
          const qlikCSS = document.createElement("link");
          qlikCSS.rel = "stylesheet";
          qlikCSS.href = `${baseUrl}/resources/autogenerated/qlik-styles.css`;
          document.head.prepend(qlikCSS);
          const requireScript = document.createElement("script");
          requireScript.src = `${baseUrl}/resources/assets/external/requirejs/require.js`;
          requireScript.onload = () => {
            let config = {
              host: qlikHost,
              prefix: qlikVirtualProxy === "" ? "/" : qlikVirtualProxy,
              port: qlikPort,
              isSecure: qlikProtocol === "https" ? true : false,
              App: e.App,
              baseUrl,
            };
            console.log("config", config);
            env.current = config;
            window.require.config({
              baseUrl: `${config.baseUrl}/resources`,
              waitSeconds: 200,
            });
            window.require(["js/qlik"], (qlik) => {
              console.log("qlik test", qlik);
              const app = qlik.openApp(config.App, config);
              app.model.waitForOpen.promise.then(() => {
                // app.model.enigmaModel.getAppProperties().then(appProps => {
                //   console.log('appProps', appProps);
                // })
                setApp(app);
                console.log(app);
                setQlikGlobal(qlik);
              });
            });
          };
          requireScript.async = true;
          document.body.appendChild(requireScript);
        });
    }
  };

  useEffect(() => {
    if (!qlikGlobal) {
      connectToQlik();
    }
  }, []);

  if (qlikGlobal && App) {
    return (
      <div className="App">
        <BrowserRouter>
          <Routes>
            <Route exact path="/" element={<Home qlikapp={App} />} />
            <Route exact path="/top-products" element={<TopProducts />} />
            <Route exact path="/map" element={<Map />} />
          </Routes>
        </BrowserRouter>

        <div class="tabs-to-dropdown">
          <div class="nav-wrapper d-flex align-items-center justify-content-between">
            <ul
              class="nav nav-pills d-none d-md-flex"
              id="pills-tab"
              role="tablist"
            >
              <li class="nav-item" role="presentation">
                <a
                  class="nav-link active"
                  id="pills-company-tab"
                  data-toggle="pill"
                  href="/"
                  role="tab"
                  aria-controls="pills-company"
                  aria-selected="true"
                >
                  Home
                </a>
              </li>
              <li class="nav-item" role="presentation">
                <a
                  class="nav-link"
                  id="pills-product-tab"
                  data-toggle="pill"
                  href="#pills-product"
                  role="tab"
                  aria-controls="pills-product"
                  aria-selected="false"
                >
                  Top Products
                </a>
              </li>
              <li class="nav-item" role="presentation">
                <a
                  class="nav-link"
                  id="pills-news-tab"
                  data-toggle="pill"
                  href="#pills-news"
                  role="tab"
                  aria-controls="pills-news"
                  aria-selected="false"
                >
                  Locations
                </a>
              </li>
            </ul>

            <ul class="list-group list-group-horizontal">
              <li class="list-group-item">
                <a href="mailto:greg@websy.io">
                  <svg
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      fill-rule="evenodd"
                      clip-rule="evenodd"
                      d="M3.00977 5.83789C3.00977 5.28561 3.45748 4.83789 4.00977 4.83789H20C20.5523 4.83789 21 5.28561 21 5.83789V17.1621C21 18.2667 20.1046 19.1621 19 19.1621H5C3.89543 19.1621 3 18.2667 3 17.1621V6.16211C3 6.11449 3.00333 6.06765 3.00977 6.0218V5.83789ZM5 8.06165V17.1621H19V8.06199L14.1215 12.9405C12.9499 14.1121 11.0504 14.1121 9.87885 12.9405L5 8.06165ZM6.57232 6.80554H17.428L12.7073 11.5263C12.3168 11.9168 11.6836 11.9168 11.2931 11.5263L6.57232 6.80554Z"
                      fill="currentColor"
                    />
                  </svg>
                </a>
              </li>
            </ul>
          </div>

          <div class="tab-content" id="pills-tabContent">
            <div
              class="tab-pane fade show active"
              id="pills-company"
              role="tabpanel"
              aria-labelledby="pills-company-tab"
            >
              <img
                className="wholefoods-logo"
                src={require("./Images/whole-foods-logo-2021-promo.jpg")}
                alt={"wholefoods-logo"}
                height="80px"
              />

              <div class="container-fluid">
                <h1 class="mb-1 font-weight-bold">Performance Overview</h1>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce
                  porttitor leo nec ligula viverra, quis facilisis nunc
                  vehicula. Maecenas purus orci, efficitur in dapibus vel,
                  rutrum in massa. Sed auctor urna sit amet eros mattis
                  interdum. Integer imperdiet ante in quam lacinia, a laoreet
                  risus imperdiet.
                </p>
              </div>
              <QlikObject
                objectId="sKEpw"
                elementId="sKEpw"
                style={{ height: "300px" }}
                qlikApp={App}
              ></QlikObject>

              <QlikObject
                objectId="eNxKep"
                elementId="eNxKep"
                style={{ height: "300px" }}
                qlikApp={App}
              ></QlikObject>
            </div>
            <div
              class="tab-pane fade"
              id="pills-product"
              role="tabpanel"
              aria-labelledby="pills-product-tab"
            >
              <div class="container-fluid">
                <h2 class="mb-3 font-weight-bold">Top Products</h2>
                <p>
                  Sed auctor urna sit amet eros mattis interdum. Integer
                  imperdiet ante in quam lacinia, a laoreet risus imperdiet. Ut
                  a blandit elit, vitae volutpat nunc. Nam posuere urna sagittis
                  lectus eleifend viverra. Quisque mauris nunc, viverra vitae
                  sodales non, auctor in diam. Sed dignissim pulvinar sapien sed
                  fermentum. Praesent interdum turpis ut neque tristique ornare.
                  Nam dictum est sed sem elementum rutrum. Nam a mollis turpis.
                </p>
                <p>
                  Proin odio nisi, aliquet ac ipsum quis, auctor semper leo.
                  Curabitur vitae justo vel augue varius cursus non quis est.
                  Nunc vulputate nunc nibh, sed tempus erat tincidunt eget. Duis
                  a lacus at nulla porttitor tincidunt. Vestibulum euismod
                  elementum mi ut tincidunt. Suspendisse tempus, mi et imperdiet
                  maximus, est turpis placerat massa, at venenatis sem elit ut
                  ex. Donec non aliquam odio. Curabitur ut leo vitae magna
                  lobortis accumsan. Phasellus viverra eu leo non rhoncus.
                </p>
                <p>
                  Pellentesque rutrum sit amet nunc sit amet faucibus. Ut id
                  arcu tempus, varius erat et, ornare libero. In quis felis
                  nunc. Aliquam euismod lacus a eros ornare, ut aliquam sem
                  mattis. Cras non varius dui, quis commodo ante. Maecenas
                  gravida est non nulla malesuada egestas.
                </p>
              </div>
            </div>
            <div
              class="tab-pane fade"
              id="pills-news"
              role="tabpanel"
              aria-labelledby="pills-news-tab"
            >
              <div class="container-fluid">
                <h2 class="mb-3 font-weight-bold">Locations</h2>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce
                  porttitor leo nec ligula viverra, quis facilisis nunc
                  vehicula. Maecenas purus orci, efficitur in dapibus vel,
                  rutrum in massa. Sed auctor urna sit amet eros mattis
                  interdum. Integer imperdiet ante in quam lacinia, a laoreet
                  risus imperdiet.
                </p>
                <p>
                  Proin maximus iaculis rhoncus. Morbi ante nibh, facilisis
                  semper faucibus consequat, facilisis ut ante. Mauris at nisl
                  vitae justo auctor imperdiet. Cras sodales, justo sed
                  tincidunt venenatis, ante erat ultricies eros, at mollis eros
                  lorem ac mi. Fusce sagittis nibh nunc. Vestibulum ante ipsum
                  primis in faucibus orci luctus et ultrices posuere cubilia
                  curae; Donec mollis eros sodales convallis faucibus.
                  Vestibulum sit amet odio lectus. Duis eu dolor vitae est
                  venenatis viverra eu sit amet nisl. Aenean vel sagittis odio.
                  Quisque in lacus orci. Etiam ut odio lobortis odio consectetur
                  ornare.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  } else {
    return <div>loading</div>;
  }
}

export default App;
